## Extracting text 

In [2]:
from pdfminer.high_level import extract_text, extract_pages
t = extract_text("file.pdf")
print(t)

Compiler Design Project 

Semester: Fall 2023 

Project Title: Mini Compiler 

Project Description: In this project, you will develop a mini compiler that performs 
lexical analysis, syntax analysis, and basic semantic analysis for  assembly (MIPS) 
programming language.  

Project Phases: 

1.  Lexical Analysis 

2.  Syntax Analysis 

3.  Semantic Analysis 

Notes: 

• You should identify the tokens classes in a way that will help you in the 
following phase (parser) 

• You can use any programming language you prefer for building the scanner. 

• The project deadline for phase 1 is 2/12 and discussion during (3/12 – 7/12) 

• Each team should be 3 to 4 members 

• A discussion will be with all group members; all members should participate in 
implementation. 

• Very important: any plagiarism detected will lead to losing the project marks  

The details of each phase are given below. 

1 | P a g e  

 
 
 
 
 
 
 
 
 
Lexical Analysis: 

 

Implement a lexical analyzer (scanner) th

## Extracting Images

In [3]:
import fitz
import PIL.Image
import io
import numpy as np

pdf = fitz.open("z.pdf")
for page in pdf: # get each page of pdf file
    for imageData in page.get_images(): # get all images in pdf
        image = pdf.extract_image(imageData[0])
        extractedImage = PIL.Image.open(io.BytesIO(image["image"]))
        # extractedImage = PIL.Image.open(io.BytesIO(image["image"])).show() # or write this line instead of above line to show the images
        print(np.array(extractedImage)) # printing the numpy array data which will be the input of LLM

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

## Extracting tables

In [4]:
import tabula

pdf = tabula.read_pdf("table.pdf")
pdf[2]

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'
'pages' argument isn't specified.Will extract only from page 1 by default.


Object: digizilla.module                           Unnamed: 0
0                  comments                       Comments, text
1                   company                    Company, many2one
2                   country                        Country, char
3               create_date       Created on, datetime, readonly
4                create_uid       Created by, many2one, readonly
5                 customers                 Customers, many2many
6              display_name         Display Name, char, readonly
7                    gender                    Gender, selection
8                        id                ID, integer, readonly
9              joining_date                   Joining Date, date
10                     name                           Name, char
11                    notes                          Notes, text
12                     tags                           Tags, char
13               write_date  Last Updated on, datetime, readonly
14                write_uid  Last Updated by, many2one, readonly

In [3]:
import aspose.words as aw

doc = aw.Document("z.pdf")
doc.save("Output.html")

In [18]:
import bs4 as bs

bs.BeautifulSoup(open("Output.html", "r")).p.prettify()

'<p style="margin-top:0pt; margin-bottom:0pt">\n <span style="height:0pt; display:block; position:absolute; z-index:-65537">\n  <img alt="" height="342" src="Output.001.png" style="margin-top:215.05pt; -aw-left-pos:0pt; -aw-rel-hpos:margin; -aw-rel-vpos:margin; -aw-top-pos:0pt; -aw-wrap-type:none; position:absolute" width="629"/>\n </span>\n <span style="-aw-import:ignore">\n </span>\n</p>\n'